### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by miuratv** [TouchDesigner/WebRTC-Remote-Panel-Web-Demo#15]
Hi, a clearer explanation would be nice:  i can't make this connect to nothing, there is no log, no error messages, just nothing that helps to make a working connection.  

- Is the certificate needed?  the port should be set as 443 in the signaling server in touchdesigner? 
- Can i use 9980 port in the web page? 
- the project must run on the same machine? do i need a touchdesigner with a signaling client running together?
- using the official demo do i need to open ports on the router?  

Having a more precise explanation would be better, since i can make a WebRTC between two Touchdesigner machines without issues.

**Comment by miuratv** [comment]
Using ws:// prefix instead of wss:// and the standard port makes everything a lot easier.

Also i think that linking this page would be necessary.  https://derivative.ca/community-post/experience-webrtc-and-webrtc-remote-panel-new-webrtc-remote-panel-web-demo/67004

**Comment by jetXS** [comment]
@miuratv apologies I missed this. 

443 is the default port for wss. Since the default URI is starting with wss:// it does use the port 443.

Most users would use the already running and available web demo, which is not hosted locally, they would be required to use wss://.

I'll link the page.
